site_name: Research Toolbox
site_url: https://biokt.github.io/ResDocs/
repo_url: https://github.com/BioKT/ResDocs
use_directory_urls: False 
theme: readthedocs
nav:
    - 'index.md'
    - Getting Started: 'Starting/guide.md'
    - Beast: 'Beast/installation.md'
    - Gromacs:
        - Installation: 'Gromacs/installation.md'
        - Simulation setup: 'Gromacs/md_setup.md'
        - Submission scripts: 'Gromacs/submission.md'
        - Benchmarks: 'Gromacs/benchmarks.md'
    - VMD: 'VMD/tools.md'
    - PBS: 'PBS/documentation.md'
    - Systems: 
        - 'Linux': 'Linux/admin.md'
        - 'Mac OSX': 'MacOSX/hacks.md'
    - Other: 'Other/other.md'
