site_name: Research Toolbox
site_url: https://biokt.github.io/ResDocs/
repo_url: https://github.com/BioKT/ResDocs
use_directory_urls: False 
theme: readthedocs
nav:
  - Home: 'index.md'
  - 'Molecular Dynamics':
    - 'Getting Started': 'Starting/guide.md'
    - Groacs:
      - Installation: 'Gromacs/installation.md'
      - Simulation setup: 'Gromacs/md_setup.md'
      - Submission scripts: 'Gromacs/submission.md'
      - Benchmarks: 'Gromacs/benchmarks.md'
      - PBS scripts: 'PBS/documentation.md'
    - Amber:
      - Building molecules: 'Amber/peptide.md'
    - 'VMD': 'VMD/tools.md' 
  - 'Parametrization':
    - MCPB.py:
      - Installation: 'MCPB.py/installation.md'
      - Parametrization: 'MCPB.py/parametrization.md'
      - Editing force fields: 'MCPB.py/force-field-editing.md'
  - Phylogenetic trees:
    - Beast: 'Beast/installation.md'
  - Systems: 
      - Linux:
        - 'Linux administration': 'Linux/admin.md'
      - Mac OS X:
        - 'Mac OS X hacks': 'MacOSX/hacks.md'
  - Other: 'Other/other.md'
